#!/bin/bash

exec java -server ${JAVA_ARGS} \
    -Dcom.sun.management.jmxremote \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.local.only=false \
    -XX:MaxGCPauseMillis=20 \
    -XX:InitiatingHeapOccupancyPercent=35 \
    -XX:+ExplicitGCInvokesConcurrent \
    -XX:MaxInlineLevel=15 \
    -Djava.awt.headless=true \
    -classpath .:/opt/kafka/lib/* \
    kafka.Kafka /opt/kafka/config/server.properties